	message	fox,<qiuj wipoj, raportu''>,<--->,other	; (1) <all ships check in!>

	; unused
	message	fox,<we did it!>,<--->,other	; (2) <we did it!>
	message	fox,<slippy slippy##>,<--->,other	; (3) <slippy slippy##>
	message	fox,<go back to the base!>,<--->,other	; (4) <go back to the base!>

	message	falcon,<mi pretas, foks''>,<--->,other	; (5) <ready, fox!>
	message	falcon,<mi estas kun vi, foks''>,<--->,other	; (6) <i'm with you, fox!>
	message	falcon,<iu sekvas min''>,<--->,help	; (7) <bogey on my six!>
	message	falcon,<zorgu pri vi mem, foks''>,<--->,other	; (8) <mind your own business, fox!>
	message	falcon,<iu pafis min'' mi mortas''''>,<--->,down	; (9) <they got me! i'm gone!!>
	message	falcon,<mi pafos qiujn''>,<--->,other	; (10) <i'll blast 'em all!>
	message	falcon,<venas pli da malamikoj''>,<--->,other	; (11) <there's more on the way!>
	message	falcon3,<vi povas kuri, sed ne povas kawi vin''>,<--->,other	; (12) <you can run, but you can't hide!>
	message	falcon,<tiu estas mia''>,<-->,other	; (13) <this one's mine!>
	message	falcon,<pafu pli zorge, foks''>,<--->,help	; (14) <watch it, fox!>
	message	falcon,<iu pafis min''>,<-->,other	; (15) <i'm hit!!>
	message	falcon,<jen ili venas''>,<--->,other	; (16) <here they come!>
	message	falcon3,<malplilongigu la kolon kaj voston, foks''>,<--->,other	; (17) <make the neck and tail shorter, fox!!>
	message	falcon3,<forpafu la brakojn por trafi la korpon''>,<--->,other	; (18) <shoot down its arms to hit its body!>
	message	falcon,<malrapidixu, foks''>,<--->,other	; (19) <slow it down, fox!>
	message	falcon,<rulixu'' rulixu''>,<--->,other	; (20) <roll, baby! rock 'n roll!>

	; unused
	message	falcon,<my ship's messed up###>,<--->,other	; (21) <my ship's messed up###>

	message	falcon,<hej'' tiu estis mia''>,<--->,other	; (22) <hey! that one was mine!>
	message	falcon,<movixu'' mi pafas''>,<--->,other	; (23) <bogies, i'm comin' through!>

	; unused
	message	falcon,<i'll cover your tail!>,<--->,other	; (24) <i'll cover your tail!>

	message	rabbit,<jes ja - ek''>,<--->,other	; (25) <yeah - let's go!>
	message	rabbit,<mi sekvas vin, foks''>,<--->,other	; (26) <i'm behind you, fox!>
	message	rabbit,<perdixu, fiulo''>,<--->,help	; (27) <get lost, you fiend!>
	message	rabbit,<dankon''>,<--->,other	; (28) <yeah! thanks!>
	message	rabbit,<ve'' mi mortos''>,<--->,down	; (29) <aargh!! i'm a goner!>
	message	rabbit,<ni frakasu ilin''>,<--->,other	; (30) <let's smash 'em!>
	message	rabbit,<mi trafis'' mi trafis''>,<--->,other	; (31) <i got one! i got one!!>
	message	rabbit,<gustumu mian pafilon''>,<--->,other	; (32) <take this, enemy brute!>
	message	rabbit,<vi ne eskapos''>,<--->,other	; (33) <you're not getting away!>
	message	rabbit,<pafu pli zorge, foks''>,<--->,help	; (34) <watch your aim, fox!>
	message	rabbit,<aj'' aj''>,<--->,other	; (35) <ouch! ouch!>
	message	rabbit,<venas malamikaj wipoj''>,<--->,other	; (36) <incoming enemy craft!>
	message	rabbit3,<malplilongigu la kolon kaj voston, foks''>,<--->,other	; (37) <please make the neck and tail shorter, fox!>
	message	rabbit3,<forpafu la brakojn por trafi la korpon''>,<--->,other	; (38) <shoot down its arms to hit its body!>
	message	rabbit,<la bremson'' uzu la bremson''>,<--->,other	; (39) <retros! fire retros!>
	message	rabbit,<rulixu'' deskuu xin''>,<--->,other	; (40) <roll over! shake it off!>

	;unused
	message	rabbit,<pick me up on your way back!>,<--->,other	; (41) <pick me up on your way back!>

	message	rabbit,<hej'' tiu estis mia''>,<--->,other	; (42) <hey! he was mine!>
	message	rabbit,<movixu''>,<--->,other	; (43) <out of my way!>

	; unused
	message	rabbit,<i'm off your starboard!>,<--->,other	; (44) <i'm off your starboard!>

	message	frog,<bone''>,<--->,other	; (45) <ok!!>
	message	frog,<kvak'' mi flugas malanta!e''>,<--->,other	; (46) <ribbit! i'll bring up the rear, fox!>
	message	frog,<kvak'' helpu min''>,<--->,help	; (47) <croak! help me!>
	message	frog,<kvak'' dankon pro la helpo''>,<--->,other	; (48) <ribbit! thanks fer the save!>
	message	frog,<ne'' ne'' kkvvaakk''>,<--->,down	; (49) <no! no! crrooakk!>
	message	frog,<mi pafos xin'' kvak''>,<--->,other	; (50) <i'll get him -- ribbit!>
	message	frog,<facilege''>,<--->,other	; (51) <piece of c-c-cake!>
	message	frog,<g-g-gustumu la malvenkon''>,<--->,other	; (52) <take this, j-j-junk heap!>
	message	frog,<mi pafos qi tiun'' kvak''>,<--->,other	; (53) <i'll get this one! ribbit!>
	message	frog,<hej'' estas mi, glitqjo''>,<--->,other	; (54) <hey! it's me, slippy!>
	message	frog,<kvak'' iu pafis min''''>,<--->,other	; (55) <ribbit! i'm hit!!>
	message	frog,<estas tro multaj''>,<--->,other	; (56) <there's too many of them!>
	message	frog,<qu ni retirixu?>,<--->,other	; (57) <let's turn back, okay?!>
	message	frog,<ni estu singardaj''>,<--->,other	; (58) <let's be careful!>
	message	frog,<io alkroqixas al mi''>,<--->,other	; (59) <something's sticking to me!>

	; unused
	message	frog,<i c-c-couldn't go, fox!>,<--->,other	; (60) <i c-c-couldn't go, fox!>

	message	frog,<hej'' ne estu t-t-tiel avara''>,<--->,other	; (61) <hey! don't be so g-g-greedy!>
	message	frog,<for, idioto- idistoj''>,<--->,other	; (62) <c-c-clear out, astro-geeks!>

	; unused
	message	frog,<hope there's no more!>,<--->,other	; (63) <hope there's no more!>

	message	frog,<qu vi vidis?>,<--->,other	; (64) <did you see me?>

	;unused
	message	rabbit,<i can't tell which is real!!>,<--->,other	; (65) <i can't tell which is real!!>

	message	falcon,<ni eniru''>,<--->,other	; (66) <let's head in!>
	message	rabbit,<mi sekvos vin''>,<--->,other	; (67) <i'll follow you in!>
	message	frog,<qu ni eniru?>,<--->,other	; (68) <should we go in?!>
	message	falcon,<###qi tiu povus esti problemo###>,<--->,help	; (69) <###this one could be trouble###>
	message	rabbit,<rapidu''>,<--->,help	; (70) <hurry!>
	message	frog,<rapidu, foks'' kvak''>,<--->,help	; (71) <hurry up, fox! croak!>
	message	falcon,<okulojn anta!en, foks''>,<--->,other	; (72) <eyes forward, fox!>
	message	rabbit,<atentu, foks''>,<--->,other	; (73) <be careful, fox!>
	message	frog,<qi-foje mi savis vin''>,<--->,other	; (74) <this time, i saved you!>
	message	falcon,<senprobleme, foks''>,<--->,other	; (75) <no sweat, fox!>
	message	rabbit,<kien ni iras nun?>,<--->,other	; (76) <ok, ok! what's next?!>
	message	frog,<qio estas b-b-bona''>,<--->,other	; (77) <so far, so g-g-good!>
	message	frog,<rigardu min''>,<--->,other	; (78) <look, look!>
	message	falcon,<qio en ordo, foks''>,<--->,other	; (79) <it's looking good, fox!>
	message	rabbit,<ni sukcesis''>,<--->,other	; (80) <we did it, let's go!>
	message	frog,<b-b-bonege''>,<--->,other	; (81) <g-g-great!>
	message	falcon,<estu pli zorgema, foks''>,<--->,other	; (82) <be a bit more careful fox!>
	message	rabbit,<zorgeme anta!en, foks''>,<--->,other	; (83) <please tread carefully, fox!>
	message	frog,<memoru, ne p-p-pafu min''>,<--->,help	; (84) <remember not to shoot m-m-me!>
	message	falcon,<ne iras bone''>,<--->,help	; (85) <it's going pretty badly!>
	message	rabbit,<mi timas, ke mi mortos''>,<--->,help	; (86) <i don't think i'm going to make it!>
	message	frog,<mia wipo disixas### kvak''>,<--->,help	; (87) <my ship's falling apart### ribbit!>

	message	fox,<teamo stelvulpo, nia lasta espero estas kontra!ataki venenon'' bonwancon''>,<--->,other	; (88) <star fox team, our last resort is to counter attack venom! good luck!>
	message	fox,<la armeo de androso intencas konstrui militbazon en qi tiu loko'' detruu ilian rokrompilon''>,<--->,other	; (89) <andross's forces intend to build a base in this area! destroy their rock crusher!>
	message	fox,<la kosma militwiparo konsistas el fortaj batalwipoj'' detruu iliajn fontojn de energio''>,<--->,other	; (90) <the space armada consists of powerful battleships! destroy their energy cores!>
	message	fox,<nepre uzu viajn bremsojn, se vi tro rapidas'' atentu pri miaj arvingoj''>,<--->,other	; (91) <be sure to use your retros if you're going too fast! be careful with my arwings!>
	message	fox,<androso kawas sin sur veneno'' foks, vi devas trovi lian kernan cerbon kaj detrui xin''>,<--->,other	; (92) <andross is hiding on venom! fox, you must find his core brain and destroy it!>

	message	fox,<        KORNERIO - LA BAZO>,<--->,other	; (93) <CORNERIA - THE BASE>
	message	fox,<          ASTEROIDA ZONO>,<--->,other	; (94) <ASTEROID BELT>
	message	fox,<            SEKTORO X>,<--->,other	; (95) <SECTOR X>
	message	fox,<         PLANEDO FORTUNO>,<--->,other	; (96) <THE PLANET FORTUNA>
	message	fox,<        KOSMA MILITWIPARO>,<--->,other	; (97) <THE ANDROSS SPACE ARMADA>
	message	fox,<         PLANEDO TITANIO>,<--->,other	; (98) <THE PLANET TITANIA>
	message	fox,<      LA TERURA NIGRA TRUO>,<--->,other	; (99) <THE AWESOME BLACK HOLE>
	message	fox,<            SEKTORO Y>,<--->,other	; (100) <SECTOR Y>
	message	fox,<      METEOROIDA BATALBAZO>,<--->,other	; (101) <THE BATTLE BASE METEOR>
	message	fox,<            SEKTORO  Z>,<--->,other	; (102) <SECTOR Z>
	message	fox,<         PLANEDO MAKBETO>,<--->,other	; (103) <THE PLANET MACBETH>
	message	fox,<         VENENO - LA CELO>,<--->,other	; (104) <VENOM - THE FINAL GOAL>
	message	fox,<    EKSTERE DE QI TIU DIMENSIO>,<--->,other	; (105) <OUT OF THIS DIMENSION>

	message	fox,<la risursoplena planedo titanio estas okupita'' rekaptu la veteroregan aparaton''>,<--->,other	; (106) <corneria's resource world has been overrun! you must re-take the weather control unit!>
	message	fox,<kiel stirixas la arvingoj?       se amebo alkroqas sin al via wipo, premu l a! r por deskui xin#>,<--->,other	; (107) <how are the arwings handling? if an amoeba clings to your ship, use l or r to get rid of it#>
	message	fox,<vi elektis la trian trakon### tio estas bona elekto por surprizi venenon''>,<--->,other	; (108) <you've chosen course three###  a good choice to take venom by surprise!>
	message	fox,<premu l a! r por eskapi de la malamika batalwipa tirradio''>,<--->,other	; (109) <use the l or r button to escape the tractor beam of the enemy battleship! you can do it, fox!>
	message	fox,<androso prenis kontrolon de la grandaj bestoj de fortuno'' estu zorgema, foks''>,<--->,other	; (110) <andross has taken control of the huge creatures who live on fortuna! take care, fox!>
	message	fox,<via teamo bone progresas, foks'' mi esperas, ke vi zorgas pri miaj arvingoj'' ek al makbeto''>,<--->,other	; (111) <your team is doing well, fox! i hope you're taking good care of my arwings! go for macbeth!>
	message	fox,<la kava interno de makbeto tre ta!gas por militbazo'' malebligu, ke androso konstruos tie''>,<--->,other	; (112) <the hollow interior of macbeth is ideal for a base! prevent andross from building here!>
	message	fox,<jen la kosma tombejo, kreita de la eksperimentoj de androso, kie malaperis via patro, foks''>,<--->,other	; (113) <this space grave yard, created by andross's experiments, is where your father vanished, fox!>
	message	fox,<qu qiuj bonstatas, foks? vi kawe alvenas al la bazo de veneno''>,<--->,other	; (114) <is everyone all right, fox?! you're on course to sneak into venom's back door!>
	message	fox,<respondu, arvingoj'' kie vi estas, foks? ni bezonas vin protekti kornerion''>,<--->,other	; (115) <come in, arwings!  fox, where are you?!  we need you to protect corneria!>
	message	fox,<vi persistis xis nun### venki androson estas via sorto'' ni dependas je vi, foks''>,<--->,other	; (116) <you've made it this far### it's your fate to destroy andross! we're counting on you, fox!>

	message	falcon,<mi detruos la aviportan wipon''>,<--->,other	; (117) <the attack-carrier will be mine!>

	message	pepper3,<nu, foks'' ni vidu vian kapablon''>,<--->,other	; (118) <ok, fox! let's see your real ability!>
	message	rabbit3,<ni devas traflugi qiujn ringojn''>,<--->,other	; (119) <we've got to fly through all the rings!>
	message	pepper,<mi rekomendas agordon a a! b''>,<--->,other	; (120) <i recommend you use control type a or b!>
	message	pepper,<ha, vi estas tre lerta, foks''>,<--->,other	; (121) <ahhh### you are quite skillful, fox!>
	message	pepper3,<vi sukcesis''  nun alfrontu  la malamikon''>,<--->,other	; (122) <ok, you passed! go fight the real enemy!>
	message	frog3,<premu start   por reveni al   la ludo, kvak''>,<--->,other	; (123) <hit start to go back to the game, ribbit!>
	message	falcon3,<nekredeble, ke pipro testas nin''>,<--->,other	; (124) <i can't believe pepper has to test us!>
	message	pepper3,<pardonu min pro mia dubo'' premu start''>,<--->,other	; (125) <i'm sorry i doubted you! press start!>

	message	andross,<foks, vi ja batalas kuraxe###>,<--->,other	; (126) <fox, you are indeed a worthy foe###>
	message	andross3,<tamen, via malsaxa penado estas vana''>,<--->,other	; (127) <but, your foolish efforts are futile!>
	message	andross3,<viaj arvingoj neniel povas venki min''>,<--->,other	; (128) <your arwings have no chance against me!>
	message	andross3,<mi pensis, ke vi eble iam alvenos###>,<--->,other	; (129) <i thought you might make it eventually###>
	message	andross,<generalo pipro bone gvidis vin''>,<--->,other	; (130) <general pepper has guided you well!>
	message	andross,<tamen, vi ne eskapos vivaj''>,<--->,other	; (131) <however, you will not escape here alive!>
	message	andross3,<ho### via vojelekto surprizis min''>,<--->,other	; (132) <ah## your choice of routes took me by surprise!>
	message	andross3,<anka! via        patro batalis senprudente''>,<--->,other	; (133) <your father was a reckless fighter too###>
	message	andross3,<sed nun venos la fino de la makla!doj''>,<--->,other	; (134) <but this will be the mccloud's last battle!>

	message	falcon,<sekvu min, foks''>,<--->,other	; (135) <follow me, fox!>
	message	falcon,<rulixu, foks'' rulixu''>,<--->,other	; (136) <roll, fox! rock'n roll!>
	message	rabbit,<restu en formacio''>,<--->,other	; (137) <stay in formation!>
	message	falcon,<kio estas al vi hodia!, foks?>,<--->,other	; (138) <what's wrong with you today, fox?!>
	message	frog3,<vi estas b-b-bonega, foks''>,<--->,other	; (139) <yer g-g-great, fox! ribbit!>

	message	falcon3,<gardu vin kontra! la granda rajo''>,<--->,other	; (140) <beware of the big stingray!>
	message	rabbit3,<gardu vin kontra! la granda rajo''>,<--->,other	; (141) <beware of the big stingray!>
	message	frog3,<gardu vin kontra! la granda rajo''>,<--->,other	; (142) <beware of the big stingray!>
