	;<all ships check in!>
	message	fox,<qiuj wipoj, raportu vin''>,<--->,other	; (1)

	; unused
	message	fox,<we did it!>,<--->,other	; (2)
	message	fox,<slippy slippy##>,<--->,other	; (3)
	message	fox,<go back to the base!>,<--->,other	; (4)

	;<ready, fox!>
	message	falcon,<mi pretas, foks''>,<--->,other	; (5)
	;<i'm with you, fox!>
	message	falcon,<mi estas kun vi, foks''>,<--->,other	; (6)
	;<bogey on my six!>
	message	falcon,<io sekvas min''>,<--->,help	; (7)
	;<mind your own business, fox!>
	message	falcon,<zorgu pri vi mem, foks''>,<--->,other	; (8)
	;<they got me! i'm gone!!>
	message	falcon,<iu pafis min'' mi mortas''''>,<--->,down	; (9)
	;<i'll blast 'em all!>
	message	falcon,<mi pafos qiujn''>,<--->,other	; (10)
	;<there's more on the way!>
	message	falcon,<venas pli da malamikoj''>,<--->,other	; (11)
	;<you can run, but you can't hide!>
	message	falcon,<vi povas kuri, sed ne povas kawi vin''>,<--->,other	; (12)
	;<this one's mine!>
	message	falcon,<mi pafos xin''>,<-->,other	; (13)
	;<watch it, fox!>
	message	falcon,<atentu, foks''>,<--->,help	; (14)
	;<i'm hit!!>
	message	falcon,<iu pafis min''>,<-->,other	; (15)
	;<here they come! >
	message	falcon,<jen ili venas''>,<--->,other	; (16)
	;<make the neck and tail shorter, fox!!>
	message	falcon3,<malplilongigu la kolon kaj voston, foks''>,<--->,other	; (17)
	;<shoot down its arms to hit its body!>
	message	falcon3,<forpafu la brakojn por trafi la korpon''>,<--->,other	; (18)
	;<slow it down, fox!>
	message	falcon,<malrapidixu, foks''>,<--->,other	; (19)
	;<roll, baby! rock 'n roll!>
	message	falcon,<rulixu'' rulixu''>,<--->,other	; (20)

	; unused
	message	falcon,<my ship's messed up###>,<--->,other	; (21)

	;<hey! that one was mine!>
	message	falcon,<hej'' mi pafus tion''>,<--->,other	; (22)
	;<bogies, i'm comin' through!>
	message	falcon,<movixu'' mi pafas''>,<--->,other	; (23)

	; unused
	message	falcon,<i'll cover your tail!>,<--->,other	; (24)

	;<yeah - let's go!>
	message	rabbit,<jes ja - ek''>,<--->,other	; (25)
	;<i'm behind you, fox!>
	message	rabbit,<mi sekvas vin, foks''>,<--->,other	; (26)
	;<get lost, you fiend!>
	message	rabbit,<perdixu, fiulo''>,<--->,help	; (27)
	;<yeah! thanks!>
	message	rabbit,<dankon''>,<--->,other	; (28)
	;<aargh! i'm a goner!>
	message	rabbit,<ve'' mi mortos''>,<--->,down	; (29)
	;<let's smash 'em!>
	message	rabbit,<ni detruu ilin''>,<--->,other	; (30)
	;<i got one! i got one!!>
	message	rabbit,<mi trafis'' mi trafis''>,<--->,other	; (31)
	;<take this, enemy brute!>
	message	rabbit,<gustumu mian pafilon''>,<--->,other	; (32)
	;<you're not getting away!>
	message	rabbit,<vi ne eskapos''>,<--->,other	; (33)
	;<watch your aim, fox!>
	message	rabbit,<pafu pli zorge, foks''>,<--->,help	; (34)
	;<ouch! ouch!>
	message	rabbit,<aj'' aj''>,<--->,other	; (35)
	;<incoming enemy craft! >
	message	rabbit,<venas malamikaj wipoj''>,<--->,other	; (36)
	;<please make the neck and tail shorter, fox!>
	message	rabbit3,<malplilongigu la kolon kaj voston, foks''>,<--->,other	; (37)
	;<shoot down its arms to hit its body!>
	message	rabbit3,<forpafu la brakojn por trafi la korpon''>,<--->,other	; (38)
	;<retros!  fire retros!>
	message	rabbit,<malrapidixu''>,<--->,other	; (39)
	;<roll over! shake it off!>
	message	rabbit,<rulixu'' deskuu xin''>,<--->,other	; (40)

	;unused
	message	rabbit,<pick me up on your way back!>,<--->,other	; (41)

	;<hey! he was mine!>
	message	rabbit,<hej! mi pafus tiun''>,<--->,other	; (42)
	;<out of my way!>
	message	rabbit,<movixu''>,<--->,other	; (43)

	; unused
	message	rabbit,<i'm off your starboard!>,<--->,other	; (44)

	;<ok!!>
	message	frog,<o kej''>,<--->,other	; (45)
	;<ribbit! i'll bring up the rear,fox!>
	message	frog,<kvak'' mi flugas malanta!e, foks''>,<--->,other	; (46)
	;<croak!  help me!>
	message	frog,<kvak'' helpu min''>,<--->,help	; (47)
	;<ribbit!  thanks fer the save!>
	message	frog,<kvank'' dankon pro la helpo''>,<--->,other	; (48)
	;<no! no! crrooakk!>
	message	frog,<ne'' ne'' kkvvaakk''>,<--->,down	; (49)
	;<i'll get him -- ribbit!>
	message	frog,<mi pafos xin'' kvak''>,<--->,other	; (50)
	;<piece of c-c-cake!>
	message	frog,<tre facile''>,<--->,other	; (51)
	;<take this, j-j-junk heap!>
	message	frog,<g-g-gustumu la malvenkon''>,<--->,other	; (52)
	;<i'll get this one! ribbit!>
	message	frog,<mi pafos qi tiun'' kvak''>,<--->,other	; (53)
	;<hey! it's me, slippy!>
	message	frog,<hej'' estas mi, glitqjo''>,<--->,other	; (54)
	;<ribbit!  i'm hit!!>
	message	frog,<kvak'' iu pafis min''''>,<--->,other	; (55)
	;<there's too many of them!>
	message	frog,<ili estas tro multaj''>,<--->,other	; (56)
	;<let's turn back, okay?!>
	message	frog,<qu ni ritirixu?>,<--->,other	; (57)
	;<let's be careful!>
	message	frog,<ni estu zorgemaj''>,<--->,other	; (58)
	;<something's sticking to me!>
	message	frog,<io alkroqixas al mi''>,<--->,other	; (59)

	; unused
	message	frog,<i c-c-couldn't go, fox!>,<--->,other	; (60)

	;<hey! don't be so g-g-greedy!>
	message	frog,<hej'' ne estu t-t-tiel avida''>,<--->,other	; (61)
	;<c-c-clear out, astro-geeks!>
	message	frog,<ni venkos''>,<--->,other	; (62)

	; unused
	message	frog,<hope there's no more!>,<--->,other	; (63)

	;<did you see me?>
	message	frog,<qu vi vidis min?>,<--->,other	; (64)

	;unused
	message	rabbit,<i can't tell which is real!!>,<--->,other	; (65)

	;<let's head in!>
	message	falcon,<ni eniru''>,<--->,other	; (66)
	;<i'll follow you in!>
	message	rabbit,<mi sekvos vin''>,<--->,other	; (67)
	;<should we go in?!>
	message	frog,<qu ni eniru?>,<--->,other	; (68)
	;<###this one could be trouble###>
	message	falcon,<###qi tiu povus esti problemo###>,<--->,help	; (69)
	;<hurry!>
	message	rabbit,<rapidixu''>,<--->,help	; (70)
	;<hurry up, fox!  croak!>
	message	frog,<rapidixu, foks'' kvak''>,<--->,help	; (71)
	;<eyes forward, fox!>
	message	falcon,<rigardu anta!en, foks''>,<--->,other	; (72)
	;<be careful, fox!>
	message	rabbit,<atentu, foks''>,<--->,other	; (73)
	;<this time, i saved you!>
	message	frog,<qi-foje, mi savis vin''>,<--->,other	; (74)
	;<no sweat, fox!>
	message	falcon,<senprobleme, foks''>,<--->,other	; (75)
	;<ok, ok! what's next?!>
	message	rabbit,<kien ni iras nun?>,<--->,other	; (76)
	;<so far, so g-g-good!>
	message	frog,<qio estas b-b-bona''>,<--->,other	; (77)
	;<look, look!>
	message	frog,<rigardu'' rigardu''>,<--->,other	; (78)
	;<it's looking good, fox!>
	message	falcon,<qio estas bona, foks''>,<--->,other	; (79)
	;<we did it, let's go!>
	message	rabbit,<ni sukcesis'' ek''>,<--->,other	; (80)
	;<g-g-great!>
	message	frog,<b-b-bone''>,<--->,other	; (81)
	;<be a bit more careful, fox!>
	message	falcon,<estu pli zorgema, foks''>,<--->,other	; (82)
	;<please tread carefully, fox!>
	message	rabbit,<zorgeme anta!en, foks''>,<--->,other	; (83)
	;<remember not to shoot m-m-me!>
	message	frog,<memoru ne p-p-pafu min''>,<--->,help	; (84)
	;<it's going pretty badly!>
	message	falcon,<estas malbone''>,<--->,help	; (85)
	;<i don't think i'm going to make it!>
	message	rabbit,<mi timas, ke mi mortos''>,<--->,help	; (86)
	;<my ship's falling apart### ribbit!>
	message	frog,<mia wipo difektixas### kvak''>,<--->,help	; (87)

	;<star fox team, our last resort is to counter attack venom!  good luck!>
	message	fox,<teamo stelvulpo, nia lasta rimedo estas kontra!ataki venenon'' bonan wancon''>,<--->,other	; (88)
	;<andross's forces intend to build a base in this area!  destroy their rock crusher!>
	message	fox,<la armeo de androso intencas konstrui militbazon en qi tiu loko'' detruu ilian rokpulvigilon''>,<--->,other	; (89)
	;<the space armada consists of powerful battleships! destroy their energy cores!>
	message	fox,<la kosma militwiparo konsistas el fortaj batalwipoj'' detruu iliajn fontojn de energio''>,<--->,other	; (90)
	;<be sure to use your retros if you're going too fast!  be careful with my arwings!>
	message	fox,<nepre uzu viajn retrigilojn, se vi tro rapidas'' atentu pri miaj arvingoj''>,<--->,other	; (91)
	;<andross is hiding on venom!  fox, you must find his core brain and destroy it!>,
	message	fox,<androso kawas sin qe veneno'' foks, vi devas trovi lian kernan cerbon kaj detrui xin''>,<--->,other	; (92)

	message	fox,<        KORNERIO - LA BAZO>,<       CORNERIA - THE BASE>,other	; (93)
	message	fox,<          ASTEROIA ZONO>,<          ASTEROID BELT>,other	; (94)
	message	fox,<            SECTORO X>,<             SECTOR  X>,other	; (95)
	message	fox,<         PLANEDO FORTUNO>,<      THE PLANET FORTUNA>,other	; (96)
	message	fox,<        KOSMA MILITWIPARO>,<    THE ANDORF SPACE ARMADA>,other	; (97)
	message	fox,<         PLANEDO TITANIO>,<       THE PLANET TITANIA>,other	; (98)
	message	fox,<      LA TIMINDA NIGRA TRUO>,<     THE AWESOME BLACK HOLE>,other	; (99)
	message	fox,<            SECTORO Y>,<             SECTOR  Y>,other	; (100)
	message	fox,<      METEOROIDA BATALBAZO>,<     THE BATTLE BASE METEOR>,other	; (101)
	message	fox,<            SECTORO  Z>,<             SECTOR  Z>,other	; (102)
	message	fox,<         PLANEDO MAKBETO>,<       THE PLANET MACBETH>,other	; (103)
	message	fox,<         VENENO - LA CELO>,<     VENOM - THE FINAL GOAL>,other	; (104)
	message	fox,<    EKSTERE DE QI TIU DIMENSIO>,<     OUT OF THIS DIMENSION>,other	; (105)

	;<corneria's resource world has been overrun!  you must re-take the weather control unit!>
	message	fox,<la rimedoplena planedo titanio estas okupigita'' rekaptu la veterokontrolan aparaton''>,<--->,other	; (106)
	;<how are the arwings handling?  if an amoeba clings to your ship, use l or r to get rid of it#>
	message	fox,<kiel stirixas la arvingoj? se amebo kroqas vian wipon, premu l a! r por desku xin#>,<--->,other	; (107)
	;<you've chosen course three###  a good choice to take venom by surprise!>
	message	fox,<vi elektis la trian trakon### tio estas bona elekto por surprizi venenon''>,<--->,other	; (108)
	;<use the l or r button to escape the tractor beam of the enemy battleship! you can do it, fox!>
	message	fox,<premu l a! r por eskapi de la malamika batawipa tirrado''>,<--->,other	; (109)
	;<andross has taken control of the huge creatures who live on fortuna!  take care, fox!>
	message	fox,<androso prenis kontrolon de la grandaj bestoj de fortuno'' estu zorgema, foks''>,<--->,other	; (110)
	;<your team is doing well, fox!  i hope you're taking good care of my arwings!  go for macbeth!>
	message	fox,<via teamo bone progresas, foks'' mi esperas, ke vi zorgas pri miaj arvingoj'' ek al maketo''>,<--->,other	; (111)
	;<the hollow interior of macbeth is ideal for a base!  prevent andross from building here!>
	message	fox,<la kava interno de makbeto tre ta!gas por militbazo'' malebligu, ke androso konstruos tie''>,<--->,other	; (112)
	;<this space grave yard, created by andross's experiments, is where your father vanished, fox!>,<--->,other	; (113)
	message	fox,<jen la kosma tombejo, kreita de la eksperimentoj de androso, kie malaperis via patro, foks''>,<--->,other	; (113)
	;<is everyone all right, fox?!  you're on course to sneak into venom's back door!>
	message	fox,<qu qiuj bonstatas, foks? vi kawe alvenas al la bazo de veneno''>,<--->,other	; (114)
	;<come in, arwings!  fox, where are you?!  we need you to protect corneria!>
	message	fox,<respondu, arvingoj'' kie vi estas, foks? ni bezonas vin protekti kornerion''>,<--->,other	; (115)
	;<you've made it this far### it's your fate to destroy andross!  we're counting on you, fox!>
	message	fox,<vi persistis xis nun### via sorto estas venki androson'' ni dependas je vi, foks''>,<--->,other	; (116)

	;unused
	message	falcon3,<the attack- carrier will be mine!>,<--->,other	; (117)

	;<ok, fox! let's see your real ability!>
	message	pepper3,<nu, foks'' ni vidu vian kapablon''>,<--->,other	; (118)
	;<we've got to fly through all the rings!>
	message	rabbit3,<ni devas flugi tra qiuj ringoj''>,<--->,other	; (119)
	;<i recommend you use control type a or b!>
	message	pepper3,<mi rekomendas agordon a a! b''>,<--->,other	; (120)
	;<ahhh### you are quite skillful,   fox!>
	message	pepper3,<ho, vi estas   tre lerta, foks''>,<--->,other	; (121)
	;<ok, you passed! go fight the real enemy!>
	message	pepper3,<vi trapasis'' nun alfrontu la malamikon''>,<--->,other	; (122)
	;<hit start to   go back to the game, ribbit!>
	message	frog3,<premu start   por reveni al   la ludo, kvak''>,<--->,other	; (123)
	;<i can't believe pepper has to test us!>
	message	falcon3,<mi ne kredas,   ke pipro testas nin''>,<--->,other	; (124)
	;<i'm sorry         i doubted you! press start!>
	message	pepper3,<pardonu min pro mia dubo'' premu start''>,<--->,other	; (125)

	;<fox,           you are indeed a worthy foe###>
	message	andross3,<foks,          vi estas respektinda###>,<--->,other	; (126)
	;<but, your foolish efforts are futile!>
	message	andross3,<tamen, via malsaxa penado estas vana''>,<--->,other	; (127)
	;your arwings have no chance against me!>
	message	andross3,<viaj arvingoj neniel povas venkimin''>,<--->,other	; (128)
	;<i thought you might make it eventually###>
	message	andross3,<mi pensis, ke vi iam alvenos###>,<--->,other	; (129)
	;<general pepper has guided you well!>
	message	andross3,<generalo pipro bone gvidis vin''>,<--->,other	; (130)
	;<however, you will not escape here alive!>
	message	andross3,<tamen, vi ne eskapos de qi tie''>,<--->,other	; (131)
	;<ah## your choice of routes took me by surprise!>
	message	andross3,<ho### via vojelekto surprizis min''>,<--->,other	; (132)
	;<your father was a reckless fighter too###>
	message	andross3,<anka! via patro estis senprudenta batalanto###>,<--->,other	; (133)
	;<but this will be the mccloud's last battle!>
	message	andross3,<sed nun okazos la fina batalo de la makkla!doj''>,<--->,other	; (134)

	;<follow me, fox!>
	message	falcon,<sekvu min, foks''>,<--->,other	; (135)
	;falcon,<roll, fox! rock'n roll!>
	message	falcon3,<rulixu, foks'' rulixu''>,<--->,other	; (136)
	;rabbit,<stay in formation!>
	message	rabbit3,<restu en formacio''>,<--->,other	; (137)
	;<what's wrong with you today, fox?!>
	message	falcon3,<kio okazis al vi hodia!, foks?>,<--->,other	; (138)
	;<yer g-g-great, fox! ribbit!>
	message	frog,<vi estas b-b-bonega, foks''>,<--->,other	; (139)

	;<beware of the big stingray!>
	message	falcon,<gardu vin kontra! la granda rajo''>,<--->,other	; (140)
	message	rabbit,<gardu vin kontra! la granda rajo''>,<--->,other	; (141)
	message	frog,<gardu vin kontra! la granda rajo''>,<--->,other	; (142)
